{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "hibernator.fullname" . }}-runner
  labels:
    {{- include "hibernator.labels" . | nindent 4 }}
    app.kubernetes.io/component: runner
rules:
  - apiGroups: ["hibernator.ardikabs.com"]
    resources: ["cloudproviders", "k8sclusters"]
    verbs: ["get"]

  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]

  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "create", "update", "patch"]
{{- end }}
