{{- if and .Values.rbac.create .Values.runnerServiceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hibernator.runnerServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hibernator.labels" . | nindent 4 }}
    app.kubernetes.io/component: runner
  {{- with .Values.runnerServiceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
