apiVersion: v2
name: hibernator
description: A Helm chart for Hibernator Operator - Kubernetes-native time-based infrastructure hibernation.
type: application
version: 1.2.0
appVersion: 1.2.1
keywords:
  - kubernetes
  - operator
  - hibernation
  - infrastructure
  - cloud
  - cost-optimization
home: https://github.com/ardikabs/hibernator
sources:
  - https://github.com/ardikabs/hibernator
maintainers:
  - name: ardikabs
    email: me@ardikabs.com
    url: https://github.com/ardikabs
