apiVersion: v2
name: hibernator
description: A Helm chart for Hibernator Operator - Kubernetes-native time-based infrastructure hibernation
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - kubernetes
  - operator
  - hibernation
  - infrastructure
  - eks
  - rds
  - ec2
home: https://github.com/ardikabs/hibernator
sources:
  - https://github.com/ardikabs/hibernator
maintainers:
  - name: Ardika Saputro
    email: ardika@example.com
